"""add_staff_advances_to_finance

Revision ID: 0d697329769b
Revises: 4febf6738800
Create Date: 2026-07-11 18:12:03.687046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0d697329769b'
down_revision: Union[str, None] = '4febf6738800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenditures', sa.Column('staff_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenditures_staff_id'), 'expenditures', ['staff_id'], unique=False)
    op.create_foreign_key('fk_expenditures_staff_id_staff', 'expenditures', 'staff', ['staff_id'], ['id'])
    op.add_column('payrolls', sa.Column('advances', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrolls', 'advances')
    op.drop_constraint('fk_expenditures_staff_id_staff', 'expenditures', type_='foreignkey')
    op.drop_index(op.f('ix_expenditures_staff_id'), table_name='expenditures')
    op.drop_column('expenditures', 'staff_id')
    # ### end Alembic commands ###
