"""add_term_installment_templates

Revision ID: 4febf6738800
Revises: d3e4f5a6b7c8
Create Date: 2026-07-10 21:12:24.558927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4febf6738800'
down_revision: Union[str, None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_installment_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('milestones', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_installment_templates_id'), 'term_installment_templates', ['id'], unique=False)
    op.create_index(op.f('ix_term_installment_templates_term_id'), 'term_installment_templates', ['term_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_term_installment_templates_term_id'), table_name='term_installment_templates')
    op.drop_index(op.f('ix_term_installment_templates_id'), table_name='term_installment_templates')
    op.drop_table('term_installment_templates')
    # ### end Alembic commands ###
