"""add_student_registration_medical_aboutme_reportcard

Revision ID: 7d60463bb444
Revises: 65fc5e13c945
Create Date: 2026-04-24 21:46:15.442057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d60463bb444'
down_revision: Union[str, None] = '65fc5e13c945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_card_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('times_school_opened', sa.Integer(), nullable=True),
    sa.Column('times_present', sa.Integer(), nullable=True),
    sa.Column('times_late', sa.Integer(), nullable=True),
    sa.Column('interest_curiosity', sa.String(length=1), nullable=True),
    sa.Column('level_of_attention', sa.String(length=1), nullable=True),
    sa.Column('interrelation_peers', sa.String(length=1), nullable=True),
    sa.Column('personal_cleanliness', sa.String(length=1), nullable=True),
    sa.Column('self_confidence', sa.String(length=1), nullable=True),
    sa.Column('expression_ability', sa.String(length=1), nullable=True),
    sa.Column('indoor_outdoor_play', sa.String(length=1), nullable=True),
    sa.Column('environment_awareness', sa.String(length=1), nullable=True),
    sa.Column('class_teacher_comment', sa.Text(), nullable=True),
    sa.Column('head_teacher_comment', sa.Text(), nullable=True),
    sa.Column('next_term_begins', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'term_id', 'session_id', name='uq_report_card_meta')
    )
    op.create_index(op.f('ix_report_card_meta_id'), 'report_card_meta', ['id'], unique=False)
    op.create_table('student_about_me',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('been_in_childcare', sa.Boolean(), nullable=True),
    sa.Column('childcare_terminated_reason', sa.Text(), nullable=True),
    sa.Column('is_extremely_active', sa.Boolean(), nullable=True),
    sa.Column('does_child_talk', sa.Boolean(), nullable=True),
    sa.Column('speaks_other_language', sa.Boolean(), nullable=True),
    sa.Column('other_language', sa.String(length=50), nullable=True),
    sa.Column('word_water', sa.String(length=50), nullable=True),
    sa.Column('word_mama', sa.String(length=50), nullable=True),
    sa.Column('word_sleep', sa.String(length=50), nullable=True),
    sa.Column('other_words', sa.Text(), nullable=True),
    sa.Column('eats_regular_food', sa.Boolean(), nullable=True),
    sa.Column('about_to_introduce_food', sa.Boolean(), nullable=True),
    sa.Column('best_food', sa.String(), nullable=True),
    sa.Column('is_picky_eater', sa.Boolean(), nullable=True),
    sa.Column('picky_eater_strategy', sa.Text(), nullable=True),
    sa.Column('has_known_allergy', sa.Boolean(), nullable=True),
    sa.Column('known_allergies', sa.Text(), nullable=True),
    sa.Column('allergy_instructions', sa.Text(), nullable=True),
    sa.Column('easy_to_fall_asleep', sa.Boolean(), nullable=True),
    sa.Column('easily_startled_sleeping', sa.Boolean(), nullable=True),
    sa.Column('sleep_helpers', sa.Text(), nullable=True),
    sa.Column('disposition_waking', sa.String(length=20), nullable=True),
    sa.Column('diaper_cream', sa.Text(), nullable=True),
    sa.Column('what_upsets_child', sa.Text(), nullable=True),
    sa.Column('what_makes_child_happy', sa.Text(), nullable=True),
    sa.Column('has_health_problem', sa.Boolean(), nullable=True),
    sa.Column('health_problem_description', sa.Text(), nullable=True),
    sa.Column('needs_regular_medication', sa.Boolean(), nullable=True),
    sa.Column('medication_details', sa.Text(), nullable=True),
    sa.Column('child_scared_of', sa.Text(), nullable=True),
    sa.Column('filled_by', sa.String(), nullable=True),
    sa.Column('form_filled_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_student_about_me_id'), 'student_about_me', ['id'], unique=False)
    op.create_table('student_medical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('bmi', sa.String(length=20), nullable=True),
    sa.Column('immunization_age_appropriate', sa.Boolean(), nullable=True),
    sa.Column('immunization_complete', sa.Boolean(), nullable=True),
    sa.Column('has_asthma', sa.Boolean(), nullable=True),
    sa.Column('has_allergies', sa.Boolean(), nullable=True),
    sa.Column('has_sight_issues', sa.Boolean(), nullable=True),
    sa.Column('has_hearing_issues', sa.Boolean(), nullable=True),
    sa.Column('has_epilepsy', sa.Boolean(), nullable=True),
    sa.Column('has_bleeding_disorder', sa.Boolean(), nullable=True),
    sa.Column('has_fear_phobia', sa.Boolean(), nullable=True),
    sa.Column('on_medications', sa.Boolean(), nullable=True),
    sa.Column('had_major_surgery', sa.Boolean(), nullable=True),
    sa.Column('medical_details', sa.Text(), nullable=True),
    sa.Column('eye_left', sa.String(length=50), nullable=True),
    sa.Column('eye_right', sa.String(length=50), nullable=True),
    sa.Column('hearing_left', sa.String(length=50), nullable=True),
    sa.Column('hearing_right', sa.String(length=50), nullable=True),
    sa.Column('dental', sa.String(length=100), nullable=True),
    sa.Column('chest_exam', sa.String(length=100), nullable=True),
    sa.Column('abdomen_exam', sa.String(length=100), nullable=True),
    sa.Column('blood_hbsag', sa.String(length=20), nullable=True),
    sa.Column('blood_hiv', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('blood_genotype', sa.String(length=10), nullable=True),
    sa.Column('urinalysis', sa.String(length=100), nullable=True),
    sa.Column('stool_microscopy', sa.String(length=100), nullable=True),
    sa.Column('is_fit_for_activities', sa.Boolean(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_student_medical_id'), 'student_medical', ['id'], unique=False)
    op.create_table('student_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('father_full_name', sa.String(), nullable=True),
    sa.Column('father_occupation', sa.String(), nullable=True),
    sa.Column('father_genotype', sa.String(length=10), nullable=True),
    sa.Column('father_state', sa.String(), nullable=True),
    sa.Column('father_local_government', sa.String(), nullable=True),
    sa.Column('father_age', sa.Integer(), nullable=True),
    sa.Column('father_work_address', sa.Text(), nullable=True),
    sa.Column('father_house_address', sa.Text(), nullable=True),
    sa.Column('father_phone', sa.String(length=20), nullable=True),
    sa.Column('mother_full_name', sa.String(), nullable=True),
    sa.Column('mother_occupation', sa.String(), nullable=True),
    sa.Column('mother_genotype', sa.String(length=10), nullable=True),
    sa.Column('mother_state', sa.String(), nullable=True),
    sa.Column('mother_local_government', sa.String(), nullable=True),
    sa.Column('mother_age', sa.Integer(), nullable=True),
    sa.Column('mother_work_address', sa.Text(), nullable=True),
    sa.Column('mother_house_address', sa.Text(), nullable=True),
    sa.Column('mother_phone', sa.String(length=20), nullable=True),
    sa.Column('child_genotype', sa.String(length=10), nullable=True),
    sa.Column('child_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_student_registration_id'), 'student_registration', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_registration_id'), table_name='student_registration')
    op.drop_table('student_registration')
    op.drop_index(op.f('ix_student_medical_id'), table_name='student_medical')
    op.drop_table('student_medical')
    op.drop_index(op.f('ix_student_about_me_id'), table_name='student_about_me')
    op.drop_table('student_about_me')
    op.drop_index(op.f('ix_report_card_meta_id'), table_name='report_card_meta')
    op.drop_table('report_card_meta')
    # ### end Alembic commands ###
