"""add_grade_scale

Revision ID: 8daa525ee38c
Revises: 9f1a2b3c4d5e
Create Date: 2026-07-08 16:58:35.759338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8daa525ee38c'
down_revision: Union[str, None] = '9f1a2b3c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remark', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_scales_id'), 'grade_scales', ['id'], unique=False)
    op.alter_column('paystack_transactions', 'status',
               existing_type=postgresql.ENUM('INITIALIZED', 'PENDING', 'SUCCESS', 'FAILED', name='paystacktransactionstatus'),
               nullable=True,
               existing_server_default=sa.text("'INITIALIZED'::paystacktransactionstatus"))
    op.alter_column('paystack_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('paystack_transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paystack_transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('paystack_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('paystack_transactions', 'status',
               existing_type=postgresql.ENUM('INITIALIZED', 'PENDING', 'SUCCESS', 'FAILED', name='paystacktransactionstatus'),
               nullable=False,
               existing_server_default=sa.text("'INITIALIZED'::paystacktransactionstatus"))
    op.drop_index(op.f('ix_grade_scales_id'), table_name='grade_scales')
    op.drop_table('grade_scales')
    # ### end Alembic commands ###
