"""add_attendance_checkin_and_installments

Revision ID: a720db5c511b
Revises: d9e0f1a2b3c4
Create Date: 2026-07-06 18:11:49.447654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
revision: str = 'a720db5c511b'
down_revision: Union[str, None] = 'd9e0f1a2b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_fee_installment_plans_id'), 'fee_installment_plans', ['id'], unique=False)
    op.create_table('fee_installment_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', name='installmentmilestonestatus'), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['fee_installment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_installment_milestones_id'), 'fee_installment_milestones', ['id'], unique=False)
    op.add_column('attendance', sa.Column('check_in_time', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('check_out_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'check_out_time')
    op.drop_column('attendance', 'check_in_time')
    op.drop_index(op.f('ix_fee_installment_milestones_id'), table_name='fee_installment_milestones')
    op.drop_table('fee_installment_milestones')
    op.drop_index(op.f('ix_fee_installment_plans_id'), table_name='fee_installment_plans')
    op.drop_table('fee_installment_plans')
    # ### end Alembic commands ###
