"""add_staff_bank_details

Revision ID: c678ba63ace8
Revises: 8daa525ee38c
Create Date: 2026-07-09 13:09:32.337423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c678ba63ace8'
down_revision: Union[str, None] = '8daa525ee38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('bank_code', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('account_name', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('paystack_recipient_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'paystack_recipient_code')
    op.drop_column('staff', 'account_name')
    op.drop_column('staff', 'bank_code')
    op.drop_column('staff', 'account_number')
    op.drop_column('staff', 'bank_name')
    # ### end Alembic commands ###
